services:
  - type: web
    name: 75flow
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn flow75.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
    # System dependencies for Pillow
    packages:
      - libjpeg-dev
      - libpng-dev
      - libfreetype6-dev
      - liblcms2-dev
      - libwebp-dev
      - libtiff5-dev
      - libopenjp2-7-dev
      - libxcb1-dev
