# Generated by Django 5.1 on 2025-07-14 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habitday_date_alter_habitday_day_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
