# Generated by Django 5.2.4 on 2025-07-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_category_unique_together_remove_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, help_text='Email for weekly stats notifications', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weekly_stats_enabled',
            field=models.BooleanField(default=True, help_text='Receive weekly stats emails'),
        ),
    ]
