# Generated by Django 5.1 on 2025-07-14 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_profile_email_profile_weekly_stats_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('streak', 'Streak'), ('completion', 'Completion'), ('category', 'Category'), ('milestone', 'Milestone')], max_length=20)),
                ('icon', models.CharField(default='ri-medal-line', max_length=50)),
                ('color', models.CharField(default='#ffd700', max_length=7)),
                ('requirement_value', models.IntegerField(help_text='Value required to earn this achievement')),
                ('requirement_type', models.CharField(choices=[('days', 'Days'), ('streak', 'Streak'), ('completion_percentage', 'Completion Percentage'), ('categories_completed', 'Categories Completed')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('achievement', 'Achievement'), ('streak', 'Streak'), ('reminder', 'Reminder'), ('milestone', 'Milestone'), ('weekly_report', 'Weekly Report')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
