# Generated by Django 5.1 on 2025-07-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_achievement_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='requirement_type',
            field=models.CharField(choices=[('days', 'Days'), ('streak', 'Streak'), ('completion_percentage', 'Completion Percentage'), ('categories_completed', 'Categories Completed')], max_length=30),
        ),
    ]
