# Generated by Django 5.2.4 on 2025-07-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_alter_achievement_requirement_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
