# Generated by Django 4.2.7 on 2025-09-04 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import habits.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0009_delete_achievement_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (JPG, PNG, GIF up to 5MB)', null=True, upload_to=habits.models.profile_image_path),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('general', 'General Feedback'), ('feature_request', 'Feature Request'), ('improvement', 'Improvement Suggestion'), ('other', 'Other')], default='general', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('steps_to_reproduce', models.TextField(help_text='Detailed steps to reproduce the bug')),
                ('expected_behavior', models.TextField(help_text='What should happen?')),
                ('actual_behavior', models.TextField(help_text='What actually happened?')),
                ('severity', models.CharField(choices=[('low', 'Low - Minor issue'), ('medium', 'Medium - Moderate impact'), ('high', 'High - Significant impact'), ('critical', 'Critical - App breaking')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=15)),
                ('browser_info', models.CharField(blank=True, help_text='Browser and version', max_length=100)),
                ('device_info', models.CharField(blank=True, help_text='Device type and OS', max_length=100)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='bug_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
