# Generated by Django 4.2.7 on 2025-09-04 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0010_alter_profile_profile_image_feedback_bugreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Current streak in days')),
                ('best_streak', models.PositiveIntegerField(default=0, help_text='Best streak achieved')),
                ('last_reset_date', models.DateTimeField(auto_now_add=True, help_text='When streak was last reset')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-current_streak', '-updated_at'],
                'unique_together': {('user',)},
            },
        ),
    ]
