# Generated by Django 4.2.7 on 2025-09-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0011_streak'),
    ]

    operations = [
    ]
