# Generated by Django 4.2.7 on 2025-09-08 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0012_auto_20250908_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='habitday',
            options={'ordering': ['-day', 'habit__name']},
        ),
        migrations.AlterUniqueTogether(
            name='habitday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='habit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_habits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='habitday',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='habit_days', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='habitday',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_days', to='habits.habit'),
        ),
        migrations.AlterUniqueTogether(
            name='habit',
            unique_together={('category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='habitday',
            unique_together={('user', 'habit', 'day')},
        ),
        migrations.RemoveField(
            model_name='habit',
            name='user',
        ),
    ]
