#!/bin/bash

echo "🆓 75Flow - Free Deployment Script"
echo "=================================="

# Check if git is initialized
if [ ! -d ".git" ]; then
    echo "❌ Git repository not found. Please initialize git first:"
    echo "   git init"
    echo "   git add ."
    echo "   git commit -m 'Initial commit'"
    exit 1
fi

echo "✅ Project is ready for free deployment!"
echo ""
echo "🎯 Choose your free platform:"
echo ""
echo "1. 🚂 Railway (Recommended - 5 minutes)"
echo "   - Go to: https://railway.app"
echo "   - Sign up with GitHub (no credit card)"
echo "   - Click 'New Project' → 'Deploy from GitHub repo'"
echo "   - Select this repository"
echo "   - Railway will auto-deploy!"
echo ""
echo "2. 🎨 Render (Alternative - 5 minutes)"
echo "   - Go to: https://render.com"
echo "   - Sign up with GitHub (no credit card)"
echo "   - Click 'New +' → 'Web Service'"
echo "   - Connect your GitHub repository"
echo "   - Build Command: pip install -r requirements.txt"
echo "   - Start Command: gunicorn flow75.wsgi:application"
echo ""
echo "🔑 Generate a secret key:"
echo "python3 -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
echo ""
echo "📋 Environment variables to set:"
echo "SECRET_KEY=your-generated-secret-key"
echo "DEBUG=False"
echo "ENVIRONMENT=production"
echo "ALLOWED_HOSTS=*.railway.app (for Railway) or *.onrender.com (for Render)"
echo ""
echo "👥 Users ready to use:"
echo "- Shruti / Shruti123"
echo "- Sid / Sid123"
echo "- Sanju / Sanju123"
echo ""
echo "📱 Mobile-ready features:"
echo "✅ Responsive design for all devices"
echo "✅ Touch-friendly interface"
echo "✅ Fast loading on mobile"
echo ""
echo "🚀 Your app will be live in minutes - completely free!" 